Seu primeiro bot para o telegram
tableless/tableless-static pull request #18
Opened 2017-05-05 18:45 UTC by rafaelvicio

2017-05-07 18:38 UTC, diegoeis reviewed
@rafaelvicio Bem legal o tem do artigo.
Fiz algumas observações. Pode dar uma olhada?

2017-05-07 18:38 UTC, diegoeis commented on content/posts/seu-primeiro-bot-para-o-telegram.md
> +excerpt: Os BOTS de chats hoje ja são uma realidade, eles ja estão presente nos aplicativos de mensagens do seu celular, e com certeza voce ja ficou curioso em como alguns deles são desenvolvidos. Ne
`já` sem acento.
`presente` no singular, o certo é plural.
`voce` sem acento.

Sugiro que o **excerpt** seja apenas:
_Nesse artigo vamos mostrar o desenvolvimento de um BOT muito simples utilizando a API do Telegram._

2017-05-07 18:38 UTC, diegoeis commented on content/posts/seu-primeiro-bot-para-o-telegram.md
> +  - Bot
Acho que a tag BOT não faz sentido. Só existirá esse artigo com essa tag.

2017-05-07 18:38 UTC, diegoeis commented on content/posts/seu-primeiro-bot-para-o-telegram.md
> +# Criando seu primeiro Bot para o Telegram
Esse título pode ser retirado, já que o título principal já estará introduzindo o texto do artigo. Se não, ficará redundante.

2017-05-07 18:38 UTC, diegoeis commented on content/posts/seu-primeiro-bot-para-o-telegram.md
> +Os BOTS de chats hoje ja são uma realidade, eles ja estão presente nos aplicativos de mensagens do seu celular, e com certeza voce ja ficou curioso em como alguns deles são desenvolvidos. Nesse artig
`ja` sem acento.
palavra `presente` no singular, o certo é plural.
`voce` sem acento.

2017-05-07 18:38 UTC, diegoeis commented on content/posts/seu-primeiro-bot-para-o-telegram.md
> +Aos que estiverem interessados em continuar com os estudos de desenvolvimentos de BOT, junte-se ao nosso [grupo no Telegram](https://t.me/brbotdevs) para unir-se à comunidade.
Um pouco repetitivo. Ficaria melhor assim:
`Aos interessados em continuar os estudos sobre esse assunto, junte-se ao nosso [grupo no Telegram](https://t.me/brbotdevs).`

2017-05-07 18:38 UTC, diegoeis commented on content/posts/seu-primeiro-bot-para-o-telegram.md
> +Para fazer a instalação da API do Telegram execute o seguinte comando no terminal/prompt de comando:
Ficaria melhor:
`Execute o seguinte comando no terminal/prompt de comando, para fazer a instalação da API do Telegram:`

2017-05-07 19:32 UTC, rafaelvicio commented
Perfeito, obrigado!

2017-05-08 22:43 UTC, TailoMateus commented on content/posts/seu-primeiro-bot-para-o-telegram.md
> +O código desse projeto esta disponivel no [GitHub](https://github.com/rafaelvicio/primeiro-bot) do autor.
O correto é "disponível", com acento.

2017-05-10 16:19 UTC, danvitoriano requested changes
Oi @rafaelvicio! 
Dá uma olhada que seu artigo tá quase todo sem acentuação! Dúvidas é só falar! Abs

2017-05-10 17:55 UTC, rafaelvicio commented
E a primeira fez que estou utilizando o Pull Request, estou com dificuldade para realizar as alterações solicitadas por vocês.

2017-05-10 19:13 UTC, danvitoriano commented
Qual dúvida vc tem @rafaelvicio ?
Basicamente, você precisa pegar estes comentários que o @diegoeis e o @TailoMateus sugeriram, alterar no seu código, e comitar novamente na mesma branch no seu fork. Ele automaticamente vai alterar o código nessa Pull Request, pois ela já está aberta, e a fonte do código é a mesma branch ;) 
Se tiver mais dúvidas é só falar!

2017-05-10 20:23 UTC, rafaelvicio commented
Eu fiz outro commit com as alterações, acho que agora esta tudo correto.

2017-05-10 21:39 UTC, danvitoriano commented
Estamos quase lá @rafaelvicio ! Você só não conseguiu acentuar as diversas palavras que estão sem acento ainda! Acho que não vai ter jeito amigo, você vai ter que dar uma reler o post inteiro, pois a maioria das palavras como *já*, *disponivel*, *voce*, estão todas sem acento. Seu teclado é gringo? Porque se for treta nos avisa, que eu pego o que você já arrumou, e a gente acentua! :smile_cat:

2017-05-12 21:45 UTC, danvitoriano approved these changes

2017-05-12 21:45 UTC, merged

2017-05-12 22:14 UTC, danvitoriano commented
eu baixei seu artigo e fiz as correções necessárias @rafaelvicio.
já está publicado.