Create Indo além no Mundo React-Native.md
tableless/tableless-static pull request #22
Opened 2017-06-02 03:20 UTC by oximer

2017-06-02 14:50 UTC, shadowmaru requested changes
Algumas correções de ortografia e consistência

2017-06-02 14:50 UTC, shadowmaru commented on content/posts/Indo além no Mundo React-Native.md
> +Na internet, você encontra milhares de posts explicando como começar um projeto React-Native. Há tutoriais para todos os lados. O framework é simples e qualquer um com poucas horas irá conseguir cria
criar uma tela básica

2017-06-02 14:50 UTC, shadowmaru commented on content/posts/Indo além no Mundo React-Native.md
> +**Faremos duas "aplicações" react native rodando em um mesmo aplicativo. Uma sobre a outra.**
É bom ser consistente aqui: se escreveu `React-Native` várias vezes, mantenha durante o texto inteiro.

2017-06-02 14:50 UTC, shadowmaru commented on content/posts/Indo além no Mundo React-Native.md
> +Inicialmente você poderá ter dificuldade em visualizar um motivo para construir tal cenário, mas tenha certeza que ao final desse post sua cabeça terá idéias malucas da aplicabilidade dessa brincadei
'ideias' não tem mais acento

2017-06-02 14:50 UTC, shadowmaru commented on content/posts/Indo além no Mundo React-Native.md
> +Depois do ambiente React Native instalado na sua máquina, vamos inicializar um projeto React Native com dois arquivos um chamado _"App 1"_ e outro chamado _"App2"_.
React-Native

2017-06-02 14:50 UTC, shadowmaru commented on content/posts/Indo além no Mundo React-Native.md
> +Outro problema está relacionado a comunicação entre esses dois aplicativos. Se esses aplicativos são independentes, como eles se comunicam?
'relacionado à comunicação'  - tem crase no 'a'

2017-06-02 14:50 UTC, shadowmaru commented on content/posts/Indo além no Mundo React-Native.md
> +Eu vejo e posso detalhar mais em outros posts, mas lhes garanto que é possível colocar dois locais servidores node em sua máquina (cada um em uma porta) e ter as principais features de desenvolviment
não seria 'dois servidores node locais'?

2017-06-02 14:50 UTC, shadowmaru commented on content/posts/Indo além no Mundo React-Native.md
> +Seria possível fazer isso no IOS? Sim, mas esse post já está longo demais.
iOS

2017-06-02 14:50 UTC, shadowmaru commented on content/posts/Indo além no Mundo React-Native.md
> +**Vocês vêm alguma solução?**
vêem

2017-06-02 15:09 UTC, TailoMateus commented
Parabéns pelo post @oximer. No início do artigo você comenta: "Na internet, você encontra milhares de posts explicando como começar um projeto React-Native. Há tutoriais para todos os lados.". Seu leitor vai querer saber mais sobre o assunto. Consegue colocar algumas boas referências? Dessa forma, as pessoas vão acabar sempre voltando para o seu texto.

Obrigado por compartilhar seu conhecimento!

2017-06-02 18:11 UTC, oximer commented
@shadowmaru Obrigado pela ajuda com o português. 
@TailoMateus aproveitei e coloquei alguns materiais interessantes.

2017-06-03 21:20 UTC, diegoeis requested changes

2017-06-03 21:20 UTC, diegoeis commented on content/posts/Indo além no Mundo React-Native.md
> +image: https://cdn-images-1.medium.com/max/1000/1*M0bDjag4DJovh0imf9nYKQ.png
Tem que trocar essa imagem que está errada...
Pode colocar essa? http://i.imgur.com/oudmGva.png

2017-06-03 21:20 UTC, diegoeis commented on content/posts/Indo além no Mundo React-Native.md
> +title: Indo além no Mundo React-Native.
Retirar o ponto no final do título.

2017-06-03 21:20 UTC, diegoeis commented on content/posts/Indo além no Mundo React-Native.md
> +excerpt: Nesse artigo vou sair do óbvio e apresentar algumas coisas possíveis de se realizar com o React Native
Aqui acho que seria mais legal se fosse:
"Um estudo pessoal sobre as possibilidade do React Native."

2017-06-03 21:20 UTC, diegoeis commented on content/posts/Indo além no Mundo React-Native.md
> +  - Tecnologia e Tendências
Trocar a categoria **Tecnologia e Tendências** para **ReactJS**

2017-06-03 21:20 UTC, diegoeis commented on content/posts/Indo além no Mundo React-Native.md
> +Esse projeto pode lhe parecer um pouco maluco e sem serventia, mas lhe garanto que entendê-lo é um importante passo para compreender como o react-native realmente funciona.
Eu retiraria esse parágrafo. Se é sem serventia, porque devo ler o artigo?

2017-06-04 12:49 UTC, oximer commented
Done

2017-06-08 00:15 UTC, diegoeis approved these changes

2017-06-08 00:15 UTC, diegoeis commented
Agora é com o @shadowmaru

2017-06-08 00:30 UTC, shadowmaru approved these changes

2017-06-08 00:50 UTC, oximer commented
Uma dúvida, quando vai ser publicado?
Como fico sabendo dos analytics sobre meu post?

2017-06-08 00:55 UTC, merged

2017-06-08 00:55 UTC, diegoeis commented
Hmm, não fica sabendo, mas se perguntar, eu procuro aqui e te falo.

Vai ser publicado assim que o Build terminar. ;-)