Quando e porque criar um Open Source
tableless/tableless-static pull request #24
Opened 2017-06-07 04:24 UTC by raphaguasta

Open source é legal; devo criar um?

2017-06-08 00:20 UTC, diegoeis requested changes
Eu acho quei que eu ia ler um pouco sobre a história do Open Source... Queria saber o que é Open Source, qual diferença entre as políticas de Open Source, como se ganha dinheiro com Open Source, etc etc etc.

Acho que dá para se aprofundar mais no post.

2017-06-08 00:20 UTC, diegoeis commented on content/posts/Quando-e-porque-criar-um-Open-Source
> +image: http://imgur.com/gRkXNzr
Trocar imagem para http://i.imgur.com/gRkXNzr.png

2017-06-08 00:20 UTC, diegoeis commented on content/posts/Quando-e-porque-criar-um-Open-Source
> +# Quando e porque criar um Open Source
Acho que esse título pode tirar, porque já vai ter o título lá do parâmetro `title`

2017-06-08 00:20 UTC, diegoeis commented on content/posts/Quando-e-porque-criar-um-Open-Source
> +- Seu código está bem feito, ou pelo menos aceitável? Afinal, ninguém quer disponibilizar um código sem qualidade para o mundo.
Precisa da vírgula ali no `feito,`?

2017-06-08 13:07 UTC, TailoMateus commented on content/posts/Quando-e-porque-criar-um-Open-Source
> +categories:
Raphael, tenta revisar as categorias, você colocou ReactJS e JavaScript, sendo que apenas comentou um projeto no github.

2017-07-13 17:48 UTC, shadowmaru requested changes

2017-07-13 17:48 UTC, shadowmaru commented on content/posts/Quando-e-porque-criar-um-Open-Source
> +## Porque disponibilizar meu código?
'Por que' aqui é separado

2017-10-01 03:10 UTC, closed without merging