Media queries simples com rupture
tableless/tableless-static pull request #33
Opened 2017-07-07 03:50 UTC by guuibayer

2017-07-07 15:05 UTC, shadowmaru requested changes
Bacana o post, obrigado. Não conhecia essa ferramenta (mesmo porque não uso Stylus, hehe) e achei interessante.

Só apontei alguns erros de ortografia e estruturação dos parágrafos, ok?

Continue escrevendo 👍

2017-07-07 15:05 UTC, shadowmaru commented on content/posts/media-queries-simples-com-rupture.md
> +Antes de conhece-lo tinha o trabalho de criar mixins para minhas media queries e nem sempre me satisfaziam, até que o conheci, com uma documentação bacana em poucos minutos já estava tendo uma excele
Eu estruturaria um pouco diferente a frase:

> Antes de **conhecer o rupture, eu** tinha o trabalho de criar mixins para minhas **media queries, que nem sempre me satisfaziam**, até que o conheci. **Com uma documentação bacana, em poucos minutos** já estava tendo uma excelente produtividade, então se você já usa Stylus, use o rupture que é sucesso.

2017-07-07 15:05 UTC, shadowmaru commented on content/posts/media-queries-simples-com-rupture.md
> +Você pode encontrar e instala-lo seja com o [npm](https://www.npmjs.com/package/rupture) ou [yarn](https://yarnpkg.com/pt-BR/package/rupture).
> encontrá-lo e instalá-lo

2017-07-07 15:05 UTC, shadowmaru commented on content/posts/media-queries-simples-com-rupture.md
> +Hoje em dia, contamos com diversos frameworks, libs e utilitários para facilitar nosso desenvolvimento e também o tornando mais ágil, nessa ideia surgiu o rupture, um utilitário portado para Stylus q
> ... o tornando mais ágil. Nessa ideia surgiu...

Use pontos para separar sentenças.

2017-07-07 15:05 UTC, shadowmaru commented on content/posts/media-queries-simples-com-rupture.md
> +Nessa especificação acima, nosso breakpoints de mobile poderiam ser utilizados apenas através da string m assim como os breakpoints de tablet utilizando o t em nossos mixins.
> nosso**s** breakpoints

eu também envolveria as variáveis e strings  de código com crases: `m` e `t`

2017-07-07 15:05 UTC, shadowmaru commented on content/posts/media-queries-simples-com-rupture.md
> +A ideia era apenas mostrar algumas das facilidades que o rupture trás, te convido pra que você de uma [olhadinha no repositório](https://github.com/jescalan/rupture) que lá você encontra muitos outro
> ... que o rupture **traz**. **Convido você a dar** uma olhadinha no repositório...

2017-07-07 16:24 UTC, guuibayer commented
Obrigado pelas dicas e ter apontado os erros @shadowmaru! Realmente o rupture é uma baita lib, haha

2017-07-08 17:06 UTC, TailoMateus commented
Guilherme, consegue colocar umas boas referências sobre rupture? Seu leitor vai querer saber mais sobre o assunto. 

De resto, parabéns.

2017-07-10 13:32 UTC, guuibayer commented
@TailoMateus obrigado, atualmente coloquei apenas o link do repositório, não sei se fica mais interessante colocar o [site](http://jescalan.github.io/rupture/), encontrei algumas outras referências porém abordam uma introdução, assim como nessa publicação.

2017-07-13 17:45 UTC, shadowmaru approved these changes

2017-07-14 11:41 UTC, merged