Consumindo Web Service no Android
tableless/tableless-static pull request #63
Opened 2017-11-16 17:53 UTC by mahenrique94

Post que demonstra e ensina como consumir um web service para consultas de CEP no Android, o consumo é feito nativamente com Java, a idéia é fazer esse primeiro de forma dificil e nativa para depois no próximo post apresentar o Retrofit.

2017-11-16 20:32 UTC, shadowmaru requested changes
Matheus, tudo bem? Obrigado pelo artigo. Ele é bem detalhado e com muitos exemplos de código, isso é muito bom!

Porém, notei alguns erros de ortografia e sugeri algumas melhorias na construção das frases, ok?

Não listei todos porque eram repetições das anteriores, você pode conferir o artigo inteiro pelos mesmos ajustes? Valeu!

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +excerpt: Uma tarefa muito comúm do dia a dia seria realizar requisições HTTP e consumir Web Services, mas as vezes pode ser um tanto quanto chata pois precisa de configurações e alguns passos a serem
* Fica melhor trocar o 'seria' por 'é', assim: "Uma tarefa muito comum do dia-a-dia é realizar requisições..."
* 'comum' não tem acento
* 'às vezes' tem crase

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Uma tarefa muito comúm do dia a dia seria realizar requisições [HTTP](https://pt.wikipedia.org/wiki/Hypertext_Transfer_Protocol) e consumir *[Web Services](https://pt.wikipedia.org/wiki/Web_service)*
Mesma observação do excerpt acima.

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Para exemplo do post, vamos consumir um serviço para buscas de CEP, os passos que deveriamos seguir são:
* Fica melhor separando as frases: "... um serviço para buscas de CEP. Os passos que..."
* 'deveríamos' tem acento

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +O primeiro passo será criar o *layout* da nossa app, como o assunto do *post* refere-se ao *web service*, irei disponibilizar o layout:
Ficar melhor separando as frases: "... criar o layout da nossa app. Como o assunto do post..."

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Após adicionar esse *layout* para a *activity*, devemos ter nossa app parecido com:
'nossa app parecida com:'

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Agora que o *layout* esta pronto, podemos começar a consumir nosso serviço, para isso alguns passos devem ser seguidos, sendo eles:
* Fica melhor separando as frases: 'podemos começar a consumir nosso serviço. Para isso alguns passos..."
* 'está' tem acento

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +- Adicionar um listener no botão **Buscar CEP**
Se você está colocando as palavras em inglês em itálico, precisa aqui em *listener* também.

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Primeiro vamos começar adicionando um *listener* em nosso botão, para quando ele for **clicado** realizar alguma função, mas como podemos fazer isso ? Para trabalhar com eventos de *click* em botões
Não precisa de espaço entre 'isso' e '?'.

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Vou chamar a classe de `HttpService` pois a mesma irá consumir um serviço HTTP. Aqui entra um detalhe, toda requisição HTTP deve ser feita em *background* pelo Android, ou seja, a mesma não pode  ser
'por que' aqui é separado, pois é uma pergunta.

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +- Primeiro devemos configurar a requisição(URL, cabeçalhos e resposta)
coloque um espaço entre 'requisição' e os parênteses

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +- Durante o processo de requisição devemos aguardar o servidor responsável processa-la
'processá-la' tem acento

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +- Após o servidor processa-la podemos pegar o retorno
'processá-la' tem acento

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Beleza Matheus, agora sabemos o motivo do Android exigir que a requisição seja feita em *background* ou em segundo plano, mas como podemos fazer isso ?
não precisa do espaço entre 'isso' e '?'

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Calma, vamos devagar, para tudo tem uma explicação, sempre que extendemos a `AsyncTask` devemos passar esse três parâmetros para ela, sendo eles:
'esses três'

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +- **Segundo**: Será o tipo de parâmetro recebido no método `onProgressUpdate`(não iremos utiliza-lo, o mesmo é chamado sempre que a requisição é atualizada, ideal para barras de progresso)
'utilizá-lo' tem acento

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Repare que o terceiro parâmetro da `AsyncTask` é uma classe `CEP`, mas ainda não temos ela, então vamos cria-la:
'criá-la' tem acento

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Veja que trata apenas de uma classe para representar e armazenar as informações de nosso CEP, não tem segredo.
'Veja que se trata apenas...', precisa de um 'se' aí antes do verbo.

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Para realizar a requisição precisamos de um CEP, mas em nossa classe não recebemos ele ainda, como podemos resolver o problema ? Se nossa classe `HttpService` precisa de um CEP para funcionar, porque
* espaço entre as palavras e a interrogação
* espaço antes dos parênteses
* 'instanciada' não tem acento

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Pronto, ja conseguimos conectar, mas não basta conectar e realizar a requisição, precisamos de fato pegar a resposta e salvar em alguma variável, como podemos fazer isso ?
* 'já' tem acento
* tirar espaço antes da interrogação

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Podemos ler a resposta facilmente com a classe `Scanner ` do pacote `java.io`, ela abstrai bastante a complexidade de ler informações:
Fica melhor separando as frases: '... do pacote `java.io`. Ela abstrai bastante...'

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Beleza, estamos criando nosso `scanner` mas de onde ele vai ler as informações ? Para isso temos o método `openStream` em nossa `url`:
* precisa de uma vírgula depois de `scanner`
* tirar espaço antes da interrogação

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Como quase todas as classes do pacote `java.io`, devemos tratar a exceção para arquivos não encontrados, como já temos nosso `try catch`, precisamos apenas adicionar mais um `catch` em nosso `try`:
Fica melhor separando as frases: '... para arquivos não encontrados. Como já temos...'

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Beleza, tudo certo ? Errado, até o momento lemos a resposta e passamos para a classe `StringBuilder`, porém, lembra que o terceiro parâmetro de nosso `AsyncTask` era do tipo `CEP` ? Pois é, sendo ass
tirar espaços antes da interrogação

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Realizar a conversão de dados em Java pode ser algo trabalhoso, sabendo isso, a Google lançou uma biblioteca chamada [GSON](https://github.com/google/gson), responsável em abstrair a complexidade na
* 'usá-la' tem acento
* separar as frases

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Agora que nossa classe responsável por realizar a requisição esta pronta, podemos utilizada em *listener* de nosso botão. Caso tenha se perdido em algum passo, segue a classe completa:
* 'está' tem acento
* acho que em vez de 'utilizada' você quis dizer 'utilizá-la'

2017-11-16 20:32 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Bom, até o momento de todos os passos que deveriamos realizar:
'deveríamos' tem acento

2017-11-17 15:19 UTC, mahenrique94 commented on content/posts/consumindo_web_service_no_android.md
> +Para exemplo do post, vamos consumir um serviço para buscas de CEP, os passos que deveriamos seguir são:
Não entendi a parte "separando as frases"

2017-11-17 15:35 UTC, mahenrique94 commented
Pronto @shadowmaru realizei as correções ortográficas, só não entendi a questão de "separar as frases", o resto acredito que foi feito.

2017-11-20 13:57 UTC, TailoMateus reviewed
Olá Matheus, parabéns pelo post. 

Sugeri algumas correções de ortografia.

2017-11-20 13:57 UTC, TailoMateus commented on content/posts/consumindo_web_service_no_android.md
> +excerpt: Uma tarefa muito comúm do dia a dia é realizar requisições HTTP e consumir Web Services, mas as vezes pode ser um tanto quanto chata pois precisa de configurações e alguns passos a serem seg
Alterar: "comúm" para "comum".

2017-11-20 13:57 UTC, TailoMateus commented on content/posts/consumindo_web_service_no_android.md
> +O primeiro passo será criar o *layout* da nossa app, como o assunto do *post* refere-se ao *web service*, irei disponibilizar o layout:
Altera: "irei" para "vou"

2017-11-20 13:57 UTC, TailoMateus commented on content/posts/consumindo_web_service_no_android.md
> +Vou chamar a classe de `HttpService` pois a mesma irá consumir um serviço HTTP. Aqui entra um detalhe, toda requisição HTTP deve ser feita em *background* pelo Android, ou seja, a mesma não pode  ser
Altera "irá" para "vai"

2017-11-20 13:57 UTC, TailoMateus commented on content/posts/consumindo_web_service_no_android.md
> +Veja que no terceiro passo não sabemos quanto tempo o servidor irá levar para conseguir processar a requisição e devolver a resposta para a gente, por isso o Android exige que a requisição seja feita
Altera: "irá" por "levará" ou por "vai"

2017-11-20 13:57 UTC, TailoMateus commented on content/posts/consumindo_web_service_no_android.md
> +Veja que no terceiro passo não sabemos quanto tempo o servidor irá levar para conseguir processar a requisição e devolver a resposta para a gente, por isso o Android exige que a requisição seja feita
Altera: "devolver a resposta para a gente" para "devolver a resposta"

2017-11-21 18:44 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +excerpt: Uma tarefa muito comúm do dia a dia é realizar requisições HTTP e consumir Web Services, mas as vezes pode ser um tanto quanto chata pois precisa de configurações e alguns passos a serem seg
Faltou a crase no 'às vezes'

2017-11-21 18:45 UTC, shadowmaru commented on content/posts/consumindo_web_service_no_android.md
> +Uma tarefa muito comúm do dia a dia é realizar requisições [HTTP](https://pt.wikipedia.org/wiki/Hypertext_Transfer_Protocol) e consumir *[Web Services](https://pt.wikipedia.org/wiki/Web_service)*, ma
Faltou corrigir o 'comum' e o 'às vezes' aqui também

2017-11-21 18:53 UTC, shadowmaru commented
@mahenrique94 eu dei alguns exemplos de separação de frase. Por exemplo:

Em vez de escrever:

> Como quase todas as classes do pacote `java.io`, devemos tratar a exceção para arquivos não encontrados, como já temos nosso `try catch`, precisamos apenas adicionar mais um `catch` em nosso `try`:

Podemos escrever: 

> Como quase todas as classes do pacote `java.io`, devemos tratar a exceção para arquivos não encontrados. Como já temos nosso `try catch`, precisamos apenas adicionar mais um `catch` em nosso `try`:

Com frases mais curtas, a compreensão é melhor.

2017-11-22 10:29 UTC, mahenrique94 commented
Pronto galera, terminei todos os acertos que vocês mencionaram.

2017-11-22 14:33 UTC, shadowmaru approved these changes

2017-11-22 14:34 UTC, shadowmaru commented
@TailoMateus, mais alguma coisa?

2017-11-22 15:36 UTC, TailoMateus commented
Pra mim está ok. Só altera a data @mahenrique94 

Após podemos publicar.

2017-11-22 15:38 UTC, mahenrique94 commented
Pronto, não sabia que data alterar, então mudei para amanhã.

2017-11-23 13:47 UTC, merged