Dicas de front-end para designers
tableless/tableless-static pull request #66
Opened 2017-12-19 12:07 UTC by markusvdc

Dicas de front-end para designers visando agilizar o desenvolvimento do site e manter maior fidelidade ao layout.

2017-12-19 12:07 UTC, diegoeis commented
Deploy preview processing.

Built with commit 1b817aae9b4b2c5f5663f389c2d64af78ad20b71

https://app.netlify.com/sites/tableless/deploys/5a39011ba6188f221edffcb1

2017-12-19 18:57 UTC, shadowmaru requested changes
Legal e original o artigo. Eu já fiz uma vez um guia de recomendações para designers (principalmente de agências) para facilitar o nosso trabalho. Vou aproveitar algumas sugestões daqui.

Apontei algumas correções no seu texto, ok?

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +### Por que?
"Por quê" no final da frase tem acento. Corrigir em todas as ocorrências do texto.

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +É comum a utilização de pré-processadores no desenvolvimento dos sites, neles são definidos apelidos para as cores comuns no layout, facilitando em muitos processos no desenvolvimento.
"facilitando muitos processos"

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +É comum a utilização de pré-processadores no desenvolvimento dos sites, neles são definidos apelidos para as cores comuns no layout, facilitando em muitos processos no desenvolvimento.
"desenvolvimento dos sites, **e** neles são definidos"

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +Normalmente sites tem ícones padrões como setas e botões de fechar, que podem ser reaproveitados de outras formas. No caso das imagens serem SVG, é possível até mesmo mudar alguns atributos do elemen
"têm" no plural tem acento

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +Se informe sobre o que será administrável
"Informe-se"

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +Algumas áreas do site podem ser administráveis pelo usuário via painel. Sabendo o que será administrável, pode-se tomar vários cuidados na criação do layout. Áreas em que o texto for administrável pe
"Nas áreas em que o texto for administrável..."

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +Caso for dar continuidade na criação de outro designer ou precisar alterar o layout, procure referências dentro do próprio layout, muitas vezes você pode reaproveitar elementos que já foram criados o
Separe as frases: '... dentro do próprio layout. Muitas vezes você pode...."

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +Influência no reaproveitamento de código e melhora a usabilidade do site.
Influencia (verbo) não tem acento.

2017-12-19 18:57 UTC, shadowmaru commented on content/posts/dicas-de-front-end-para-designers.md
> +Eu iria adorar se um designer cria-se um artigo reverso com sugestões para os front-ends, alguém se candidata?
"criasse"

2017-12-19 19:37 UTC, markusvdc commented on content/posts/dicas-de-front-end-para-designers.md
> +### Por que?
@shadowmaru Ricardo foi animal a sua ajuda, muito obrigado.

2017-12-20 01:26 UTC, TailoMateus reviewed
Fala Markus, achei muito legal a ideia do artigo. 

Apontei duas correções. Parabéns pelo post, vou ficar aguardando a parte dois hehehehehe

2017-12-20 01:26 UTC, TailoMateus commented on content/posts/dicas-de-front-end-para-designers.md
> +  - Front-end
Acho que não existe a categoria "Front-end". Se não houver mesmo, pode retirar.

2017-12-20 01:26 UTC, TailoMateus commented on content/posts/dicas-de-front-end-para-designers.md
> +Algumas áreas do site podem ser administráveis pelo usuário via painel. Sabendo o que será administrável, pode-se tomar vários cuidados na criação do layout. Nas áreas em que o texto for administráve
Trocaria "Sabendo o que será administrável, " por "Com isso, " 

Evita utilizar 3 vezes a palavra "administra..." no mesmo parágrafo.

2017-12-20 18:51 UTC, shadowmaru approved these changes

2017-12-24 15:15 UTC, merged